version: '3.1'

services:
  app:
    image: mend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      PORT: 8080
      DB_TYPE: "SQL"

      PSQL_DB_HOST: "db"
      PSQL_DB_PORT: 5432
      PSQL_DB_USER: "postgres"
      PSQL_DB_PASSWORD: "postgres"
      PSQL_DB_NAME: "test"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql_migrations/20220718232600_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres