version: '3.1'

services:
  app:
    image: mend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      PORT: 8080
      DB_TYPE: "NoSQL"

      MONGO_PORT: "27017"      
      MONGO_DB_HOST: "mongo"
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "example"
      MONGO_DB_NAME: "test"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:5.0.9
    restart: always
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
